### ISSUE TITLE
Feature request: will you open the API about read/hit count in article meta info?

### ISSUE THREAD

**Issue by askender** [thematters/matters-server#1419]
RT

some articles about it:
<https://matters.news/@gonghei88/%E6%AA%A2%E8%A8%8E%E6%88%91%E7%9A%84-%E9%80%8F%E9%81%8Elikecoin%E5%92%8Cmatters%E6%8E%A8%E8%A1%8C%E6%8F%9B%E6%9B%B8-%E9%80%81%E6%9B%B8-%E8%A8%88%E5%8A%83-bafyreihkxgv4ijjd6jer2ywysfpic3fzqpnwrk5nxdes6c4n6vysogcpoa>

**Comment by devformatters** [comment]
We've add a field `readTime` in API, so closed it.
