### ISSUE TITLE
Evaluate Knex.js to Prisma migration

### ISSUE THREAD

**Issue by guoliu** [thematters/matters-server#1422]
**Is your feature request related to a problem? Please describe.**

We are currently using [Knex.js](http://knexjs.org/) without an ORM. This has provided flexibility in the beginning, but as our database schema grows more and more complex, we need a cleaner model for database objects. 

**Describe the solution you'd like**

We can migrate to [Prisma](https://www.prisma.io/), which has matured in the past few years. It automates most of the mapping between GraphQL schema and database schema, which will make our codebase much cleaner.

However, [Prisma Migrate](https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-migrate) for database migration is still experimental. We can take some risk and try it on, or keep [knex-migrate](https://github.com/sheerun/knex-migrate) for migration and then do introspection separately (see [example](https://github.com/motleyagency/prisma-knex)).

Since Knex is a query builder and Prisma is similar to an ORM, there need to be a change in design pattern. We need to decide what migration method we want to use, and what would be the easiest path switching to Prisma.

**Additional context**
Related to https://github.com/thematters/matters-server/issues/897

**Comment by devformatters** [comment]
Close it since there is no further update. We might want to review and come up a new solution.
