### ISSUE TITLE
Re-designing home page feeds

### ISSUE THREAD

**Issue by guoliu** [thematters/matters-server#1490]
**Is your feature request related to a problem? Please describe.**

Currently two home article feeds, 『熱門』and『熱議』, have vague design goals and significant overlap with each other. 『熱門』should be a collective choice for articles that are worth reading at a given moment, and 『熱議』should be a collective choice for articles that are worth discussing at a given moment.

For『熱門』, in the past we do not have a direct measurement of reading time. Now that we are recording read time, we can move away from appreciations/Likes, which does not have any cost for the actor and signifies many different things such as friendship, support or greetings, and move towards read time and donation, the former being a direct measurement of reading and the later with cost and therefore resilient to spams. We can also start recording impressions, which are the times an article card appear to our user, to calculate the efficiency of ready given a number of impressions.

『熱議』still requires more discussions. A general direction might be more focus on number of participates, number of votes on comments, or different ways of measuring weights of commenters.

**Comment by devformatters** [comment]
Closed it.
