### ISSUE TITLE
Separate webpage CDN cache for different user groups  

### ISSUE THREAD

**Issue by guoliu** [thematters/matters-server#1500]
We have been delivering one single version of SSR webpages on CDN, and certain user group refetch data for A/B test. This has slow response time. We can instead write user group in cookie, differentiate user group by cookie in CDN, and implement A/B test behind GraphQL resolvers.

- [x] write `group` to cookie: https://github.com/thematters/matters-server/blob/develop/src/common/utils/cookie.ts#L22
- [x] separate cache by `cookie.group` on CDN for certain pages (currently only homepage)
- [x] read `group` from cookie on server: https://github.com/thematters/matters-server/blob/develop/src/common/utils/getViewer.ts#L31
- [x] add new ranking migration and update naming convention: https://github.com/thematters/matters-server/issues/1490
- [ ] resolve to different ranking views according to user group in `recommendation.hottest` resolver

**Comment by devformatters** [comment]
@Carolusian @guoliu Close it since we use a slightly different approach to it. Feel free to reopen. 😎
