### ISSUE TITLE
Tag description is required for tags presented in home page

### ISSUE THREAD

**Issue by devformatters** [thematters/matters-server#1508]
To make home page looks better, tag description is required for tags presented in home page.

**Comment by devformatters** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [首頁標籤邏輯調整，description is not null 為必要條件](https://trello.com/c/wq3ob7gI/1702-%E9%A6%96%E9%A0%81%E6%A8%99%E7%B1%A4%E9%82%8F%E8%BC%AF%E8%AA%BF%E6%95%B4%EF%BC%8Cdescription-is-not-null-%E7%82%BA%E5%BF%85%E8%A6%81%E6%A2%9D%E4%BB%B6)

**Comment by devformatters** [comment]
@jeremyOk 

Here's SQL string we're using for gathering curation tag:
```sql
SELECT
    tag.*
FROM (
    SELECT
        tag.id,
        COUNT(1) AS articles,
        COALESCE(SUM(art.selected::int), 0) AS selected
    FROM
        tag
        JOIN article_tag art ON art.tag_id = tag.id
    WHERE
        tag.deleted = FALSE
        AND tag.owner != MATTY
        OR (tag.owner = MATTY AND now() - tag.created_at <= Interval '90 day')
    GROUP BY
        tag.id
) AS base
JOIN tag ON tag.id = base.id
WHERE
    base.articles >= 3
    AND (tag.description IS NOT NULL OR base.selected > 0) <--  here
```
Can you provide a new `WHERE` clause since `tag.description IS NOT NULL` will be required filter?

**Comment by jeremyOk** [comment]
`SELECT
    tag.*
FROM (
    SELECT
        tag.id,
        COUNT(1) AS articles,
        COALESCE(SUM(art.selected::int), 0) AS selected
    FROM
        tag
        JOIN article_tag art ON art.tag_id = tag.id
    WHERE
        tag.deleted = FALSE
        AND tag.owner != 81
        OR (tag.owner = 81 AND now() - tag.created_at <= Interval '90 day')
    GROUP BY
        tag.id
) AS base
JOIN tag ON tag.id = base.id
WHERE
    base.articles >= 5 and tag.description IS NOT NULL`

**Comment by devformatters** [comment]
Completed.
