### ISSUE TITLE
Creators can set up copywriting to attract users to donation

### ISSUE THREAD

**Issue by proformatters** [thematters/matters-server#1590]
<img width="476" alt="螢幕截圖 2020-11-10 下午7 40 25" src="https://user-images.githubusercontent.com/47885618/98669640-96f58b00-238c-11eb-9a02-b13ad8b1c01f.png">

**Comment by devformatters** [comment]
Points after discussion:

- The primary purpose of this is to enhance pay-wall. However, we have a different approach for that, so the need of this feature got shrunk.
- Messages should be linked to article or user. (no conclusion)
