### ISSUE TITLE
Multiple articles map to one draft

### ISSUE THREAD

**Issue by guoliu** [thematters/matters-server#1596]
There are at least two instances where multiple articles are map to the same draft, result in identical articles:
* https://matters.news/@clarinet 
* https://matters.news/@conanxin

**Comment by devformatters** [comment]
Looks like this problem exists before refactoring draft and article data structure.

```
SELECT
	*
FROM (
	SELECT
		count(id) AS count,
		draft_id
	FROM
		article
	GROUP BY
		draft_id) AS source
	JOIN article ON article.draft_id = source.draft_id
WHERE
	count > 1
ORDER BY
	source.draft_id ASC
```
