### ISSUE TITLE
Fix revision count increased by setting up tags

### ISSUE THREAD

**Issue by devformatters** [thematters/matters-server#2027]

**Comment by guoliu** [comment]
From @catdingding:


> https://github.com/thematters/matters-server/commit/a42f82797d3a1da509767d8eff631c042b4835cc 看起來像是這個commit造成的……feature？ 原本判斷要不要加修改次數的判斷拔掉了，統一+1
> 
> 外加前端同日也修改用字，感覺像是feature了 https://github.com/thematters/matters-web/commit/040e0fa104c068185d856a028a4d972737d8ed99
> 
> 
> 邏輯上應該是只想要只對circle權限修改起效沒錯 也有相關判斷
> 
> 但判斷式這行的resetCircle https://github.com/thematters/matters-server/blob/a42f82797d3a1da509767d8eff631c042b4835cc/src/mutations/article/editArticle.ts#L465 計算方法是 const resetCircle = circleGlobalId === null https://github.com/thematters/matters-server/blob/a42f82797d3a1da509767d8eff631c042b4835cc/src/mutations/article/editArticle.ts#L326
> 好像會導致非circle文章都被當成resetCircle?

**Comment by askender** [comment]
test it again, still not solved.   今天的测试结果，修改标签仍然算修改次数
(另外，标签内容并没有存入生成的ipfs页面。)
https://matters.news/@askender/%E6%B5%8B%E8%AF%95-%E6%B5%8B%E8%AF%95%E6%96%87%E7%AB%A0%E6%A0%87%E7%AD%BE%E4%BF%AE%E6%94%B9%E6%AC%A1%E6%95%B0-bafyreidlfapd7rmdrbn2eketkbajkd6xjdxjhesxykkoxxb7tzdvkqwkom
