### ISSUE TITLE
IPFS Hosting - Proxy Lambda

### ISSUE THREAD

**Issue by devformatters** [thematters/matters-server#2058]
Proxy Lambda needs to:
- Identify IPFS nodes and gather
- Detect IPFS nodes health and need of scaling
- Manage nodes list via database
- Handle requests from Matters server
- Check proxy lambda bootstrapping time (responding time)

**Comment by robertu7** [comment]
**Update**

Since we are considering an approach without [DB](https://github.com/thematters/matters-server/issues/2060#issuecomment-856452817), the Proxy (or API gateway) can use AWS ELB instead, which is simpler and more reliable than maintaining it ourselves.
