### ISSUE TITLE
[TBD] IPFS Hosting - Create db and table schema

### ISSUE THREAD

**Issue by devformatters** [thematters/matters-server#2060]
DB needs to fulfill:
- IPFS nodes management (nodes id, ip, state, disk usage and etc.)
- Pin hash map

**Comment by robertu7** [comment]
**Update:**

We won't record pinHash:ipfsNode map at this stage since:
* remove a pinned hash can via broadcasting to all nodes of the network, without knowing where the hash pinned by which node;
* fine-grained monitoring of user usage isn't a must;

**Comment by devformatters** [comment]
Close it since we need it no more.
