### ISSUE TITLE
Generalizing article and author feed

### ISSUE THREAD

**Issue by guoliu** [thematters/matters-server#2157]
Currently some developers use Matters API to retrieve all content data, then rank articles and users. Matters currently provides feeds of tags, users, articles and circles on different fields, but do not provide full list. We can:

* unify the API so that different rankings correspond to different sorting methods in arguments
* provide full list for sorting methods that do not require computation, such as newest article

The API can look like this:
```
type Recommendation {
  ...
  articles(input: {..., sort: newest | hottest | icymi})
  users(input: {..., sort: newest | hottest})
  tags(input: {..., sort: newest | hottest})
}
```

**Comment by robertu7** [comment]
need to review our API strategy first.
