### ISSUE TITLE
Duplicate a web environment running newer Node.js version for seeding users

### ISSUE THREAD

**Issue by devformatters** [thematters/matters-server#2261]
* Clone a Matters web environment with updated platform (we can use AWS default URL)
* Setup CI to deploy branch [feature/user-profile](https://github.com/thematters/matters-web/tree/feature/user-profile) into the new environment

Note for testing:
* check if there is any url not under matters.news domain remains
* test how routing work with relative path

**Comment by Carolusian** [comment]
http://www-new.matters.news/
