### ISSUE TITLE
[Email] - Users got duplicate emails of receiving donation

### ISSUE THREAD

**Issue by devformatters** [thematters/matters-server#2432]
Report is [here](https://mattersnews.slack.com/archives/GA0R09FHN/p1618590391029700).

**Comment by Carolusian** [comment]
This shall have been fixed in https://github.com/thematters/matters-server/commit/ae1005418e3f5ae6f100e2381b3166f9a2bba5d2

**Comment by devformatters** [comment]
I see. Closed it.
