### ISSUE TITLE
[Server] - Return a specific error for wallet-registered users trying to login via email

### ISSUE THREAD

**Issue by tx0c** [thematters/matters-server#2460]
should say some error like `wallet-registered users can only login via wallet`

https://matters.news/@MrLight/251685-被liker搞到自閉-bafyreigmziecksodbzatsloct5sze6a5st4pcfnvirfygyhatrl4ruph4y#Q29tbWVudDoxMDkxOTM5-Q29tbWVudDoxMDkyNTI4

**Comment by devformatters** [comment]
report
- [slack](https://mattersnews.slack.com/archives/GA0R09FHN/p1646604811978619)
