### ISSUE TITLE
[Server] - sendVerificationCode mutation keeps returning FORBIDDEN

### ISSUE THREAD

**Issue by devformatters** [thematters/matters-server#2468]
report
- [slack](https://mattersnews.slack.com/archives/CH8BLCMTN/p1647439407684179?thread_ts=1647404613.499369&cid=CH8BLCMTN)
- [slack](https://mattersnews.slack.com/archives/GA0R09FHN/p1647441618048589)

**Comment by devformatters** [comment]
Don't forget to attach PR 🙌🏻

**Comment by tx0c** [comment]
#2488 and #2478
