### ISSUE TITLE
Enhance verification code integrity

### ISSUE THREAD

**Issue by devformatters** [thematters/matters-server#2495]
### Tasks
- [ ] update verification code mechanism
- [ ] add more helpful logs and records

### References
- [slack #1](https://mattersnews.slack.com/archives/GA0R09FHN/p1660711567805549)
- [slack #2](https://mattersnews.slack.com/archives/GA0R09FHN/p1648069386060489?thread_ts=1648023100.759759&cid=GA0R09FHN)

**Comment by robertu7** [comment]
Consider replace Google ReCaptcha with Cloudflare Turnstile

**Comment by robertu7** [comment]
Consider replace Google ReCaptcha with Cloudflare Turnstile

**Comment by robertu7** [comment]
Consider replace Google ReCaptcha with Cloudflare Turnstile

**Comment by devformatters** [comment]
Close it, since we have to consider account design together. There's a new epic for improve user experiences.
