### ISSUE TITLE
Need something new to replace graphql-schema-typescript

### ISSUE THREAD

**Issue by tx0c** [thematters/matters-server#2557]
it failed building (and deploying) of the graphql-schema-typescript dependency on graphql-14

https://github.com/dangcuuson/graphql-schema-typescript/issues?q=sort:updated

the graphql-code-generator might be a good replacement:
1. https://www.graphql-code-generator.com/docs/getting-started
2. https://github.com/dotansimha/graphql-code-generator

**Comment by robertu7** [comment]
Already [implemented on client-side](https://github.com/thematters/matters-web/pull/3029), it's good timing to apply to server-side.

**Comment by robertu7** [comment]
Duplicated with https://github.com/thematters/matters-server/issues/3420
