### ISSUE TITLE
[Server] Update regex validation pattern for new tag naming rules

### ISSUE THREAD

**Issue by devformatters** [thematters/matters-server#2595]
refs
- [doc](https://paper.dropbox.com/doc/Matters--Bijv2PhAusvor8gQ4jLeT4CeAg-56s32V8tZp0PHlTObapvl#:uid=856368007009447166235153&h2=3%EF%B8%8F%E2%83%A3-%E6%A8%99%E7%B1%A4%E5%89%B5%E5%BB%BA%E8%A6%8F%E5%89%87)

blocked by
- [issue](https://github.com/thematters/matters-web/issues/2507)

**Comment by tx0c** [comment]
it's not blocked by the frontend issue thematters/matters-web#2507 but better to decouple with frontend deployment

**Comment by devformatters** [comment]
Technically, it's not blocked by frontend. But it will be UX problem if user didn't realize there's a new rule in backend.
