### ISSUE TITLE
Update API of all tags pages feed

### ISSUE THREAD

**Issue by devformatters** [thematters/matters-server#2596]
tasks
- [ ] add API of recommendation feed for both users and visitors
- [ ] update hottest feed query logic

refs
- [doc](https://paper.dropbox.com/doc/Matters--BkONZGWMxzBDbR0Vy3fSF~nYAg-vNwOJcbnJpRECzC1LxWXE)

design
- [figma](https://www.figma.com/file/oGew0i2s0N8IBm9tCpoLLI/%E8%BF%AD%E4%BB%A3%E8%A8%AD%E8%A8%88%E4%B8%AD%E7%B9%BC%E7%AB%99?node-id=3668%3A22908)

**Comment by robertu7** [comment]
any updates on this issue? @tx0c

**Comment by devformatters** [comment]
@tx0c any updates ?

**Comment by tx0c** [comment]
+!

**Comment by devformatters** [comment]
Issue requires review and rearrangement. Close it.
