### ISSUE TITLE
[Server] API of home page tag tabs

### ISSUE THREAD

**Issue by devformatters** [thematters/matters-server#2598]
tasks
- [x] design table for storing tag tab settings
- [x] API for updating tag tab settings

refs
- [doc](https://paper.dropbox.com/doc/Matters--BkMaihjPIrKPn0MoGINP_564Ag-047CncJwKJ6acvzy3cBvC#:uid=429177493518311354706199&h2=%E9%9A%8E%E6%AE%B5%E4%BA%8C)

design
- [figma](https://www.figma.com/file/oGew0i2s0N8IBm9tCpoLLI/%E8%BF%AD%E4%BB%A3%E8%A8%AD%E8%A8%88%E4%B8%AD%E7%B9%BC%E7%AB%99?node-id=3696%3A24028)

**Comment by guoliu** [comment]
Does it make more sense to be local-first, and stored in local storage?

Different clients of the same user will have different settings, but visitors can also use the same functionality.

**Comment by devformatters** [comment]
After last meeting, keep personal settings in db.
