### ISSUE TITLE
[Server] Store translated content into database

### ISSUE THREAD

**Issue by guoliu** [thematters/matters-server#2641]
We need to store translation into DB to reduce translation costs and to filter language with DB queries.

TODOs:
- [x] doc for db changes
- [x] store content in the database after translation (instead of storing in Redis)
- [ ] ~~after content is edited, if the content has been translated before, asynchronously re-request translation~~
- [x] query resolves to db instead of redis

**Comment by robertu7** [comment]
Doc: https://www.notion.so/matterslab/i18n-edfbade687c74c759e33072a788dddfd#6c2cb0148c6042a785af9972760e9e76
