### ISSUE TITLE
[Server] i18n for hottest feed, newest feed and featured feed

### ISSUE THREAD

**Issue by guoliu** [thematters/matters-server#2642]
Rely on: https://github.com/thematters/matters-server/issues/2656

- [ ] doc for API changes
- [ ] hottest feed 
- [ ] newest feed
- [ ] featured feed
- [ ] apply the same logic to the article feeds in tags
- [ ] check if front end is using node API for batch query

**Comment by devformatters** [comment]
Close it since our goal shifted.
