### ISSUE TITLE
[Server] API for managing search trends

### ISSUE THREAD

**Issue by devformatters** [thematters/matters-server#2644]
#### Tasks
- [x] Add API for blocking specific search key words in search trends
- [x] Might need a list for storing blocked key words

#### References
- [doc](https://paper.dropbox.com/doc/Matters--BmGpeKbnsw56qMwsagSXsK7xAg-TxbP3841So0PiQcFKpkCN)

**Comment by Jasmine-liang** [comment]
API [docs](https://www.dropbox.com/scl/fi/kstlzzwp0w7o5pih5dn6l/Remove-search-trend-keyword-schema.paper?dl=0&rlkey=q5y0fe3v9y2f8a1g7md022usv)
