### ISSUE TITLE
Solution to USDT (ERC-20) donation

### ISSUE THREAD

**Issue by robertu7** [thematters/matters-server#2696]
### Requirements 
* API to verify & record ERC-20 donations to DB;
* API to query ERC-20 donations from DB or on-chain (chainId, contractAddress);

### Tasks
- [ ] Design API schema based on requirements;
  * revise `payTo` or add a new mutation?
  * revise `User.wallet.transactions`?
- [ ] Output to a Notion documentation;

**Comment by devformatters** [comment]
The output doc is [here](https://www.notion.so/matterslab/API-and-database-schema-changes-926211df0d754bc785dcbca89a8d4613), so close this one. Feel free to reopen if needs
