### ISSUE TITLE
Masking elastic beanstalk environment

### ISSUE THREAD

**Issue by robertu7** [thematters/matters-server#2707]
### Scope
* matters-web
* matters-server

### Tasks
- [ ] Change Elastic Beanstalk Environment Name;
- [ ] Mask on GitHub Actions: YML file, logs;

### Discussion
https://mattersnews.slack.com/archives/C88CK7Q7L/p1661245484747309

### References
* https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#masking-a-value-in-log

**Comment by devformatters** [comment]
@gary02 It's done ?

**Comment by robertu7** [comment]
Can impl with https://github.com/thematters/developer-resource/issues/207

**Comment by robertu7** [comment]
moved back to Pending since we have reused the existing EB environment
