### ISSUE TITLE
[Server] API Error happened increasingly

### ISSUE THREAD

**Issue by devformatters** [thematters/matters-server#2735]
### Tasks
- [x] Investigate and tune
  - [ ] ~Rate limit between Cloudflare and origin server ?~
  - [ ] other causes ?

### References
- [Problem report](https://mattersnews.slack.com/archives/GA0R09FHN/p1661977760479029)

### Related Issues
- https://github.com/thematters/matters-server/issues/2600

**Comment by robertu7** [comment]
https://mattersnews.slack.com/archives/C88CK7Q7L/p1663327313080859?thread_ts=1663252506.866399&cid=C88CK7Q7L
