### ISSUE TITLE
Add `Article.hasTranslation` field

### ISSUE THREAD

**Issue by robertu7** [thematters/matters-server#2775]
**Tasks**
- [ ] Add `Article.hasTranslation(input: { language: UserLanguage })` field returns boolean;

**References**
* https://mattersnews.slack.com/archives/C88CK7Q7L/p1663306152213749?thread_ts=1663252251.445099&cid=C88CK7Q7L

**Comment by tx0c** [comment]
a better API could be:

    Article.availableTransations: [String!]


let the DB just returned already available (someone click'ed translated) ones for this article, and front-end `next/head` can use that to render proper alternative headers for SEO
