### ISSUE TITLE
Queue task for generating content feed

### ISSUE THREAD

**Issue by devformatters** [thematters/matters-server#2829]
### Tasks
- [ ] Output documentation about this queue job details, such as
  1. retry strategy
  2. possible difficulties

- [ ] Create queue tasks for generating content feed. Priority:
    1. Travloggers holders
    2. Inactive user who published articles (order by last time logged, article number)
    3. refresh old  content feed

**Comment by devformatters** [comment]
@tx0c Is it done ?

**Comment by tx0c** [comment]
replaced and done in [check-ipns-integrity](https://mattersnews.slack.com/archives/C88CK7Q7L/p1667785620710079?thread_ts=1667521550.639159&cid=C88CK7Q7L)
