### ISSUE TITLE
Fix user page tags query logics

### ISSUE THREAD

**Issue by devformatters** [thematters/matters-server#2838]
### Tasks
- [ ] Query of user page tags had been changed. Need correct back

### References
- query logic in below pic

<img  width="55%" src="https://user-images.githubusercontent.com/34237112/194817148-27acfaa6-38da-4bf8-826a-2a0e0d231ff0.png" />

- changes in codebases

<img width="55%" src="https://user-images.githubusercontent.com/34237112/195021923-c33ffccb-365e-4c83-8a14-09d90a4935ad.png" />

**Comment by tx0c** [comment]
revert part logic from 6ef216349
