### ISSUE TITLE
Non-utf8 content breaks rss.xml

### ISSUE THREAD

**Issue by devformatters** [thematters/matters-server#2841]
### Tasks
- [ ] Fix problem non-utf8 content break rss.xml

### References
- [slack](https://mattersnews.slack.com/archives/GA0R09FHN/p1665454403073759)

- broken rss error
<img width="55%" src="https://user-images.githubusercontent.com/34237112/195023914-261b38cd-c418-4319-adc4-485a3f4652ec.png" />

**Comment by tx0c** [comment]
```
line378: 



<description><![CDATA[今天有位交情不錯的朋友發了這則訊息給我：我有個朋友（台灣人）在中國工作，最近要把等值 600 萬台幣的人民幣匯回台灣來，加密貨幣有沒有什麼可行做法？看完的第一個想法是，原來是請教地下匯兌的部分啊。想想乾脆來寫文章公開分享（咦每年 150 萬想把錢從中國匯回台灣，得遵守中國的外匯...]]></description>
 
```

**Comment by robertu7** [comment]
@tx0c Has this issue been fixed?

**Comment by robertu7** [comment]
stagnant for a while, feel free to reopen.
