### ISSUE TITLE
Migrate CIDv0 to CIDv1

### ISSUE THREAD

**Issue by robertu7** [thematters/matters-server#2842]
### Background
CIDv1 can use as subdomain to access IPFS data and domain name is case-insensitive while CIDv0 is case-sensitive.

### Tasks
- [ ] Convert CIDv0 to CIDv1;
- [ ] Backward compatable for CIDv0;

### Refs
* https://docs.filebase.com/ipfs/ipfs-cids#when-to-use-cidv0-vs-cidv1

**Comment by devformatters** [comment]
Close it since no plan to this in near future.
