### ISSUE TITLE
Fix LikeCoin integration in dev env

### ISSUE THREAD

**Issue by devformatters** [thematters/matters-server#2861]
### Tasks
- [x] Fix testing account couldn't login
- [x] Fix testing account's LIKE are missing

**Comment by Carolusian** [comment]
> Fix testing account couldn't login

Likecoin has revert testnet UI to old version for login via matters-dev. The seeds shall be able to be exported via https://rinkeby.like.co/in/widget/authcore/seedwords 

> Fix testing account's LIKE are missing

Need go to testnet faucet: `#faucet-test - Get a small amount of LikeCoin for testing on testnet` in likecoin discord channel.
