### ISSUE TITLE
API of transaction filtering: purpose

### ISSUE THREAD

**Issue by devformatters** [thematters/matters-server#2902]
### Tasks
- [ ] provide a transaction filtering based on purpose type
  - all purpose
  - support
  - subscription (circles)

### References
- [Product doc](https://paper.dropbox.com/doc/Matters--BsHqX_ZFlhq_VWMAZNCCM86wAg-MdTHx6e50HcCFkSJaVUfI)
- [Design](https://www.figma.com/file/oGew0i2s0N8IBm9tCpoLLI/%E8%BF%AD%E4%BB%A3%E8%A8%AD%E8%A8%88%E4%B8%AD%E7%B9%BC%E7%AB%99?node-id=4115%3A22588)

**Comment by gary02** [comment]
API schema https://www.notion.so/matterslab/Transaction-filtering-1051f29f19994af38861694234fb213c
