### ISSUE TITLE
Give golden motor badge once user supports others 100 times

### ISSUE THREAD

**Issue by devformatters** [thematters/matters-server#2944]
### Tasks

- [ ] Automatically give golden motor badge once user supports others 100 times
- [ ] Sort out that giving is immediately or other solution

### References

- [Thread discussion](https://mattersnews.slack.com/archives/GGHTVNTA7/p1668399920813549)

**Comment by robertu7** [comment]
also https://github.com/thematters/developer-resource/issues/176
