### ISSUE TITLE
Deprecate content fields of article table

### ISSUE THREAD

**Issue by robertu7** [thematters/matters-server#2952]
### Background

A follow-up task of [article versioning](https://github.com/thematters/matters-server/pull/1510). Keeping these legacy fields on article table could [misguide](https://github.com/thematters/matters-server/issues/2906) our development.

### Related Issues
* https://github.com/thematters/matters-web/issues/3828
* https://github.com/thematters/matters-server/issues/2906

### Checklist
- [ ] remove content fields: `content`, `summary`, etc.
- [ ] remove unused fields: `upstream_id`, etc.
- [ ] ~remove `article.draft_id` (since `draft.article_id` works the same);~
- [ ] `ipns-listen-repub` is still relying on `article` table [[0]](https://github.com/thematters/ipns-listen-repub/blob/develop/lib/republish.ts#L17)

---

### Story
- https://github.com/thematters/developer-resource/issues/321

**Comment by guoliu** [comment]
`article` table act as pointers that point to different versions in `draft` table. `article` table record the newest version and metadata, while `draft` table record different version of content.
