### ISSUE TITLE
User retention architecture design

### ISSUE THREAD

**Issue by devformatters** [thematters/matters-server#2963]
### Tasks

- [ ] Design architecture of user retention mechanism

### References

- [Product doc](https://paper.dropbox.com/doc/Matters--BtYp4DKA7i65xm1SIQMcSQBXAg-QyAEdA7VMkOysMZFhQTcC)
- [Design](https://www.figma.com/file/sBMDFIslfs2Mp8oFVpNfqY/E-mail-%E9%83%B5%E4%BB%B6%E6%A8%A3%E5%BC%8F%E8%A8%AD%E8%A8%88?node-id=0%3A1&t=uMBEjbfpTWw5EHsy-1)

**Comment by gary02** [comment]
https://www.notion.so/matterslab/User-retention-fb95d55c61344c86b3de6076f3fd594d
