### ISSUE TITLE
Some published drafts are missing `article_id`

### ISSUE THREAD

**Issue by robertu7** [thematters/matters-server#2994]
### Checklist
- [ ] debug root cause
- [ ] fix bug in publication queue
- [ ] migrate db to fix record issue

### References
- [Thread discussion](https://mattersnews.slack.com/archives/GDD3U7B71/p1669871221622819?thread_ts=1669784079.561019&cid=GDD3U7B71)

**Comment by tx0c** [comment]
e.g.
- https://web-dev.matters.news/@devformatters/7275

**Comment by guoliu** [comment]
* debug root cause
* fix bug in publication queue
* migrate db to fix record issue

**Comment by guoliu** [comment]
Might be related: https://github.com/thematters/matters-server/issues/2952

**Comment by gary02** [comment]
root cause: 
https://github.com/thematters/matters-server/blob/1b9b1a612407ce5301221f3b86b8e344f031e0a5/src/connectors/queue/publication.ts#L421-L424
when any error happen in publication, only drafts are marked `error`,  articles stay `active`
