### ISSUE TITLE
Search performance benchmarking

### ISSUE THREAD

**Issue by devformatters** [thematters/matters-server#3054]
### Tasks
- [ ] Use k6 for testing

**Comment by gary02** [comment]
load test output: https://app.slack.com/client/T7ACZJS22/C88CK7Q7L/thread/C88CK7Q7L-1672417360.855719

**Comment by gary02** [comment]
api slow issue search https://app.slack.com/client/T7ACZJS22/C88CK7Q7L/thread/C88CK7Q7L-1672757960.369329
