### ISSUE TITLE
Setup database read-write splitting

### ISSUE THREAD

**Issue by robertu7** [thematters/matters-server#3112]
### Tasks
- [x] Research & Solution
- [ ] Setup database read-write splitting
- [ ] Apply to [Top SQL](https://ap-southeast-1.console.aws.amazon.com/rds/home?region=ap-southeast-1#performance-insights-v20206:/resourceId/db-NZFFY7USL32AY7N372GIEQRYEI/resourceName/matters-prod/startTime/1676870797481/endTime/1676957197481/presetKey/24h/presetUnit/hour/presetAmount/24) of matters-server

**Comment by gary02** [comment]
https://www.notion.so/matterslab/Read-write-Splitting-f2c02873f14c4f6e87a24e01ebcb6697
