### ISSUE TITLE
Some notices are missing

### ISSUE THREAD

**Issue by devformatters** [thematters/matters-server#3174]
### Tasks

- [x] Check why not showing below notices
  - Payout process begins
  - Article author pinned my comment
  - Someone bookmarked my article
  - Tag collaborator leave
  - Tag owner remove your article from selected feed

**Comment by gary02** [comment]
https://mattersnews.slack.com/archives/GDD3U7B71/p1677760098749879?thread_ts=1677725655.353189&cid=GDD3U7B71

**Comment by gary02** [comment]
### Someone bookmarked my article
`Someone bookmarked my article`  is off in settings by default

**Comment by gary02** [comment]
### Tag collaborator leave
it work, but only notify tag editors , but not tag followers



![Image](https://user-images.githubusercontent.com/13580441/223306227-66dba3dd-f6f9-4bbe-9322-dc0b447c98ea.png)

**Comment by gary02** [comment]
### Tag owner remove your article from selected feed

This notice type is no longer in use

https://github.com/thematters/matters-server/blob/develop/schema.graphql#L1652

**Comment by devformatters** [comment]
> ### Tag collaborator leave
> it work, but only notify tag editors , but not tag followers
> 
> ![Image](https://user-images.githubusercontent.com/13580441/223306227-66dba3dd-f6f9-4bbe-9322-dc0b447c98ea.png)

That's correct

**Comment by devformatters** [comment]
Since this card is an investigation, I'll close it.
