### ISSUE TITLE
Update API for allowing author to close response area

### ISSUE THREAD

**Issue by devformatters** [thematters/matters-server#3177]
### Tasks

- [ ] Revise GQL mutation of updating article settings 
- [ ] Change GQL query of response (return nothing if closed)

### References
- [Design](https://www.figma.com/file/oGew0i2s0N8IBm9tCpoLLI/%E8%BF%AD%E4%BB%A3%E8%A8%AD%E8%A8%88%E4%B8%AD%E7%B9%BC%E7%AB%99?node-id=11079%3A64669&t=RfsPkhvUBfn2T5VJ-1)

**Comment by gary02** [comment]
https://www.notion.so/matterslab/Article-Response-Area-Setting-25e85677e0984953b432f054d3ab41b1
