### ISSUE TITLE
Dedup articles on publication

### ISSUE THREAD

**Issue by robertu7** [thematters/matters-server#3254]
### Reports
* https://matters.canny.io/bug-reports/p/0fa964

### Tasks
* [x] Investigate and fix article publication

### References
- https://github.com/thematters/matters-server/pull/2737
- [Thread discuss](https://mattersnews.slack.com/archives/GA0R09FHN/p1679577077346339?thread_ts=1679570219.850109&cid=GA0R09FHN)

**Comment by devformatters** [comment]
@robertu7 Could you provide more info about this issue. 🙏🏻

**Comment by gary02** [comment]
related fix:  https://github.com/thematters/matters-server/pull/3267
