### ISSUE TITLE
Sitemap solution

### ISSUE THREAD

**Issue by robertu7** [thematters/matters-server#3362]
### Tasks
- [x] Provide a solution to generate and host a sitemap;
  - how to generate a large sitemap file? generate in real-time or periodic build? support incremental update?
  - which format? XML or plain text?
  - costs of implementation and maintenance?
- [ ] Output to Notion documentation;

### Refs
* https://developers.google.com/search/docs/crawling-indexing/sitemaps/build-sitemap
* https://github.com/ekalinin/sitemap.js
* https://github.com/iamvishnusankar/next-sitemap
* https://matterslab.slack.com/archives/C88CK7Q7L/p1684781487900909

**Comment by tx0c** [comment]
we can start with daily build sitemap, which includes all current 600k+ urls (~400k articles, 100k user pages, 100k tag pages)

https://developers.google.com/search/docs/crawling-indexing/sitemaps/large-sitemaps

once google search indexes those, don't have to maintain for long time

**Comment by tx0c** [comment]
- https://vercel.com/guides/how-do-i-generate-a-sitemap-for-my-nextjs-app-on-vercel
- https://nextjs.org/learn/seo/crawling-and-indexing/xml-sitemaps
