### ISSUE TITLE
Retire ethers.js

### ISSUE THREAD

**Issue by robertu7** [thematters/matters-server#3372]
### Checklist
- [x] Replace ethers.js/eth-sig-util with viem
  - [x] `connector/blockchain/curation`
  - [x] `mutation/user/claimLogbook`
  - [x] `mutation/user/generateSigningMessage`
  - [x] `types/__test__/walletLogin.test`
  - [x] uses of `utils.isAddress` / `recoverPersonalSignature`
- [ ] ~~Store case sensitive ETH address instead of lowercased~~
- [ ] ~~Migrate old eth addresses~~

### Refs
* https://viem.sh/
* https://matterslab.slack.com/archives/C88CK7Q7L/p1684997544301659

**Comment by byhow** [comment]
I can take a look at this issue if it has not been worked on yet, thanks

**Comment by robertu7** [comment]
> I can take a look at this issue if it has not been worked on yet, thanks

reassigned to you, thanks!
