### ISSUE TITLE
CI/CD testing failure

### ISSUE THREAD

**Issue by devformatters** [thematters/matters-server#3393]

**Comment by devformatters** [comment]
@gary02 done already ?

**Comment by gary02** [comment]
not yet, still processing

**Comment by gary02** [comment]
![Image](https://github.com/thematters/matters-server/assets/13580441/f6a6015b-8c32-412d-b86c-0c423f06999f)

https://github.com/thematters/matters-server/actions/runs/5110642457/jobs/9201614336
