### ISSUE TITLE
Collection & PinnedWorks API design

### ISSUE THREAD

**Issue by devformatters** [thematters/matters-server#3396]
### Checklist
- [x] Design APIs
  - Can query user collections
  - Can mutate user collections: cover, name, description, articles (orders)
  - Can query pinned works
  - Can mutate pinned works: list of articles or collections, dominant color
- [x] Output documentation

**Comment by gary02** [comment]
https://www.notion.so/matterslab/Anthology-pinned-work-085614059f8049519860dad589727a52
