### ISSUE TITLE
Bump deps: replace `graphql-schema-typescript` package with `graphql-code-generator`

### ISSUE THREAD

**Issue by gary02** [thematters/matters-server#3420]
[graphql-schema-typescript](https://github.com/dangcuuson/graphql-schema-typescript) is unmaintained since 3 years ago and do not support schema that use `@deprecated` on `INPUT_FIELD_DEFINITION`,  we can consider adopting `graphql-code-generator` package mentioned in  https://www.apollographql.com/docs/apollo-server/workflow/generate-types/

**Comment by robertu7** [comment]
Duplicated with https://github.com/thematters/matters-server/issues/2557?
