### ISSUE TITLE
Subscription pass due issue

### ISSUE THREAD

**Issue by devformatters** [thematters/matters-server#3422]
### Reports
- https://matters.canny.io/bug-reports/p/bug

### Checklists
- [x] how to handle pass due state right (grace period)
- [x] need to retry ?

### References
- https://github.com/thematters/matters-server/issues/2412

**Comment by tx0c** [comment]
- 圍爐的 狀態/收益/數據的 定期 通知 信，重要的 金流相關 給立即通知

**Comment by devformatters** [comment]
After meeting, there're no further changes for this
