### ISSUE TITLE
Social Login: solution & design

### ISSUE THREAD

**Issue by robertu7** [thematters/matters-server#3463]
### Checklist
- [x] Review PRD & design
- [x] Design new login / sign up flow
  - Do we need a table to store temporary state before username is set? or inject data (username, temp token, etc.) into the redirection URL then client-side to collect the username and submit them all at once?   
- [x] Design new API endpoints & routes for OAuth
- [x] Doc to Notion

**Comment by gary02** [comment]
https://www.notion.so/matterslab/Log-in-c1f5f866102744118c7e0b4f7b33a288
