### ISSUE TITLE
Research feasibility with Photon Storage: dag operation & ipns api

### ISSUE THREAD

**Issue by tx0c** [thematters/matters-server#3468]
- [dag operation](https://doc.gw3.io/api/gateway/dag_operation)
- [ipns](https://doc.gw3.io/api/gateway/ipns)

**Comment by jzhu-eth** [comment]
Consider using a DAG as a filesystem, where a user's current DAG root is denoted as 'A'. When a user posts a new article on Matters, follow these steps:

1. Upload the new article to the IPFS network to obtain the CID, denoted as 'X'.
2. Invoke the API at https://doc.gw3.io/api/gateway/dag_operation.html#add-to-dag. Input the current DAG root 'A', the new content CID 'X', and the path '/my_new_article'. This API will return a new DAG root, denoted as 'B'.
3. Use the API at https://doc.gw3.io/api/gateway/ipns.html#update-ipns-record to update the user's IPNS record from 'A' to 'B'.

**Comment by tx0c** [comment]
confirmed https://doc.gw3.io/api/gateway/folder.html operations working.
