### ISSUE TITLE
Stateless passphrases research

### ISSUE THREAD

**Issue by devformatters** [thematters/matters-server#3493]
### Checklist
- [x] Stateless 
- [x] Compact and self-contained 
  - OTP should be generated according to specific user and purpose
  - Maybe max 30 characters (x-x-x)
  - Specify valid period and length

**Comment by robertu7** [comment]
https://www.notion.so/matterslab/Password-based-Authentication-6335808f10f44b0c8a3e2a49bd1acbaa?pvs=4
