### ISSUE TITLE
Prohbit user withoir email to do topup and subscription

### ISSUE THREAD

**Issue by devformatters** [thematters/matters-server#3570]
### Checklist

- [ ] Update API for validation

### References
- [design](https://www.figma.com/file/IbbP1A5KbQTZiIfLAB6Sjq/%E8%A8%BB%E5%86%8A%E8%88%87%E7%99%BB%E5%85%A5?type=design&node-id=1379-11224&mode=design&t=HYMs3JHfHicAG8Bf-0)

**Comment by gary02** [comment]
https://github.com/thematters/matters-server/blob/develop/src/mutations/user/addCredit.ts#L23
https://github.com/thematters/matters-server/blob/develop/src/mutations/circle/subscribeCircle.ts#L47

had added validation on both mutations?
