### ISSUE TITLE
Slow image uploading: benchmark

### ISSUE THREAD

**Issue by devformatters** [thematters/matters-server#3572]
### Checklist
- [ ]  [One-time upload URL](https://developers.cloudflare.com/images/cloudflare-images/upload-images/direct-creator-upload/) v.s. `singleFileUpload` mutation

**Comment by tx0c** [comment]
this cloudflare direct image uploading is better way not relying on 1 single server to pass-thru the images uploading and possible bottleneck.
but direct image uploading will become each user's Web client to upload images to cloudflare directly
thematters/matters-server#3561 implemented.

**Comment by robertu7** [comment]
@tx0c have you compared between them? any insights/metrics to share?
