### ISSUE TITLE
OSS couldn't search new article

### ISSUE THREAD

**Issue by devformatters** [thematters/matters-server#3627]
### Reports
- https://feedback.matters.town/bug-reports/p/55ea78

### References
- [thread](https://matterslab.slack.com/archives/GA0R09FHN/p1695803340267989?thread_ts=1695802566.953529&cid=GA0R09FHN)

**Comment by tx0c** [comment]
some articles take longer time (than 15min) into index'ing, change default indexer-handler cronjob input parameter to scan articles deeper,
and created another job to scan deep but less often (10,000 articles per 3 hours), to balance too high cost
