### ISSUE TITLE
Referral storing

### ISSUE THREAD

**Issue by robertu7** [thematters/matters-server#3662]
### Tasks
- [ ] New table to store referees and referrers;
- [ ] New mutation for client-side to emit referral events;

### Stories
* https://github.com/thematters/developer-resource/issues/307

**Comment by tx0c** [comment]
can use Postgres JSONB single column to save those not frequently in-use columns

https://www.notion.so/matterslab/Story-Referral-Tracking-developer-resource-307-fc7970ebc4f64c32bca6bea83267932c
