### ISSUE TITLE
Design & impl API for featured feed curation

### ISSUE THREAD

**Issue by robertu7** [thematters/matters-server#3760]
### Description
CC team **can pin/unpin** articles to "Featured" feed of homepage **in the given order**, and **can write a short description** for these articles. 

### Checklist
- [x] API & DB design
- [ ] implementation

### References
* [product doc](https://www.notion.so/matterslab/8ecf4d49c2b645ff8e2efea175291f98)
* [design](https://www.figma.com/file/cF0gPX4uOBzg2w1tnji3ry/%E7%B2%BE%E9%81%B8?type=design&node-id=908-35401&mode=design&t=4z1takeGFTuGAD9H-0)

---

### Story
* https://github.com/thematters/developer-resource/issues/367

**Comment by gary02** [comment]
https://www.notion.so/matterslab/Icymi-Topic-92076753adc94b3aa13844303ec8ecde

**Comment by gary02** [comment]
https://www.notion.so/matterslab/Icymi-Topic-92076753adc94b3aa13844303ec8ecde
