### ISSUE TITLE
Add audit logs for new article detail

### ISSUE THREAD

**Issue by zeckli** [thematters/matters-server#3792]
### Description
Add audit logging for:
- Wallet connect after donation
- Support setup history, and distinguish setup history from editor and article page

### References
- [product doc](https://www.notion.so/matterslab/f0e5ab6cb5784af0943b46610af6ca2a?pvs=4#7b902ce41ee648df8ad16a472eadf5cd)

---

### Story
- https://github.com/thematters/developer-resource/issues/371

**Comment by robertu7** [comment]
moved to https://github.com/thematters/matters-web/issues/4181
