### ISSUE TITLE
re-organize mat_views.tags_view to materialized views, tear down AnalyticsDB

### ISSUE THREAD

**Issue by tx0c** [thematters/matters-server#3855]
### Description

the mat_views.tags_view was implemented as daily view because of AnalyticsDB dependencies from EMR jobs;

since EMR jobs were teared down in Mid 2023, now we can re-implement these as materialized views;

- [x] mat_views.tags_view
- [ ] ~mat_views.authors_view~
- [ ] ~mat_views.users_view~
- [ ] ~mat_views.circles_view~

- [ ] switch to the new created view

---

### Story
- https://github.com/thematters/developer-resource/issues/420

**Comment by zeckli** [comment]
Still have to switch
