### ISSUE TITLE
Add OSS UI for free wirte

### ISSUE THREAD

**Issue by gary02** [thematters/matters-server#4012]
### References
- [design](https://www.figma.com/design/vDS1dPrYuM7EHTeIaA9cPs/%E8%87%AA%E7%94%B1%E5%AF%AB?node-id=908-35401&t=DQl8IDxlKNbmRcOv-1)

---

### Story

- https://github.com/thematters/developer-resource/issues/461

**Comment by robertu7** [comment]
dups with https://github.com/thematters/matters-oss/issues/689

**Comment by robertu7** [comment]
https://github.com/thematters/matters-oss/issues/689
