### ISSUE TITLE
Clean Code: DataServices

### ISSUE THREAD

**Issue by robertu7** [thematters/matters-server#897]
DataServices such as `userService.ts` and `articleService.ts` have a lot of code in a single file, and as our business logic grows, they become difficult to maintain.

**Comment by robertu7** [comment]
https://github.com/thematters/matters-server/issues/1628

**Comment by devformatters** [comment]
Nice PR #2142 💪🏻

**Comment by gary02** [comment]
> the business logic should always stay in resolver instead of service.

But this way makes writing unit tests harder.

Furthermore， sometime, same business logics are needed by multi resolvers.  Services are  good places to store those business logic for reuse in such case.
